[package]
name = "dumpster_bench"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
authors = ["Clayton Ramsey"]
description = "Benchmark for dumpster garbage collection crate"
repository = "https://github.com/claytonwramsey/dumpster"
readme = "../README.md"
keywords = ["benchmark", "dumpster", "garbage_collector"]
categories = ["data-structures", "memory-management"]
publish = false

[dependencies]
dumpster_contains_gcs_trait = { package = "dumpster", path = "../dumpster", features = [
  "derive"
] }
dumpster_main = { package = "dumpster", git = "https://github.com/bluurryy/dumpster", branch = "master" }
dumpster_remove_contains_gcs = { package = "dumpster", git = "https://github.com/bluurryy/dumpster", branch = "remove-contains-gcs" }
fastrand = "2.0.0"
parking_lot = "0.12.3"
